apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dev
  namespace: staging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-dev
    spec:
      containers:
        - name: backend-dev
          image: 768876311475.dkr.ecr.ap-southeast-1.amazonaws.com/backend-dev:latest
          ports:
            - containerPort: 4000
          resources:
            limits:
              cpu: 600m
              memory: 768Mi
            requests:
              cpu: 200m
              memory: 384Mi
  selector:
    matchLabels:
      app: backend-dev
