apiVersion: v1
kind: Service
metadata:
  name: mongo-dev-service
  namespace: staging
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongo-dev
  type: LoadBalancer
