apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongo-dev
  namespace: staging
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2
