apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongo-prod
  namespace: production
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2
